![](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS2e1jabS-oToIuAzuf9ivtu_j0AdWrFnOP8RY1WeTnNJMooYYq)

<img src="http://www.scipy-lectures.org/_images/numpy_broadcasting.png" height="300" width="500">


<h1 align="center">Beginning with NumPy Fundamentals</h1>


## Table of Contents
- [I. Import packages](#Import-packages)
- [II. NumPy Ndarray object](#NumPy-Ndarray-object)
   - [I. Creating a multidimensional array](#Creating-a-multidimensional-array)
   - [II. Minimum dimensions](#Minimum-dimensions)
   - [III. dtype parameter](#dtype-parameter)
- [III. NumPy Data Types](#NumPy-Data-Types)
   - [I. Data Type Objects(dtype)](#Data-Type-Objects)
   - [II. Character Codes](#Character-Codes)
   - [III. Structured Data Type](#Structured-Data-Type)
   
- [IV. Array Attributes](#Array-Attributes)



## Import packages

In [1]:
import sys
from datetime import datetime
import time
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

## NumPy Ndarray object
[back to top](#Table-of-Contents)


NumPy has a multidimensional array object called ```ndarray```. It consists of two parts:
- The actual data
- Some metadata describing the data

The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ```ndarray``` takes the same size of block in the memory. Each element is an object of data-type object called **dytpe**.

Any item extracted from ```ndarray``` object(by slicing) is represented by a Python object of one of array scalar types.

*Relationship between ```ndarray```, data type object(dtype) and array scalar type*

![](https://www.tutorialspoint.com/numpy/images/ndarray.jpg)

The ```ndarray``` object can have more than one dimension.

An instance of ndarray class can be constructed by different array creation routines described later in the tutorial. The basic ndarray is created using an array function in NumPy as follows

```python
numpy.array
```

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

```python 
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

| **Parameter** | **Description**                                                                                  |
|---------------|--------------------------------------------------------------------------------------------------|
| **object**    |  Any object exposing the array interface method returns an array,  or any (nested) sequence.     |
| **dtype**     |  Desired data type of array, optional                                                            |
| **copy**      | Optional. By default (true), the object is copied                                                |
| **order**     | C (row major) or F (column major) or A (any) (default)                                           |
| **subok**     | By default, returned array forced to be a base class array.  If true, sub-classes passed through |
| **ndimin**    | Specifies minimum dimensions of resultant array                                                  |

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(5,)

### Creating a multidimensional array

In [5]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [6]:
m.shape

(2, 2)

In [7]:
n = np.array([np.arange(3), np.arange(3), np.arange(3)])
n

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
n.shape

(3, 3)

### Minimum dimensions

In [9]:
a = np.array(np.arange(5), ndmin=2)
a

array([[0, 1, 2, 3, 4]])

### dtype parameter

In [10]:
a = np.array(np.arange(5), dtype=complex)
a

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j])

The **```ndarray```** object consists of contiguous one-dimensional segment of computer memory, combined with an indexing scheme that maps each item to a location in the memory block. The memory block holds the elements in a row-major order (C style) or a column-major order (FORTRAN or MatLab style).



## NumPy Data Types
[back to top](#Table-of-Contents)

NumPy supports a much greater variety of numerical types than Python does. The following table gives an overview of NumPy numerical types.

| **Data Types**                 | **Description**                                                                 |
|--------------------------------|---------------------------------------------------------------------------------|
| **bool_**                      |  Boolean(True or False) stored as a bit                                         |
| **int_**                       |  Default Integer type(same as C long; normally either int64 or int32)           |
| **intc**                       | Identical to C int(normally int32 or int64)                                     |
| **intp**                       | Integer used for indexing (same as C ssize_t; normally either int32 or int64)   |
| **int8**                       | Byte (-128 to 127)                                                              |
| **int16**                      | Integer (-32768 to 32767)                                                       |
| **int32**                      | Integer (-$2 ^{31}$ to $2^{31}$ -1)                                                |
| **int64**                      | Integer (-$2^{63}$ to $2^{63}$ -1)                                                |
| **uint8**                      | Unsigned integer (0 to 255)                                                     |
| **uint16**                     | Unsignedinteger (0 to 65535)                                                    |
| **uint32**                     | Unsigned integer (0 to $2 ^{32}$ - 1)                                             |
| **uint64**                     | Unsigned integer (0 to $2 ^{64}$ - 1)                                             |
| **float16**                    | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa               |
| **float32**                    | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa             |
| **float64** or **float**       | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa            |
| **complex64**                  | Complex number, represented by two 32-bit floats (real andimaginary components) |
| **complex128** or  **complex** | Complex number, represented by two 64-bit floats (real andimaginary components) |


NumPy numerical types are instances of dtype (data-type) objects , each having unique characteristics. The dtypes are available as ```np.bool_```, ```np.float32```.

### Data Type Objects
[back to top](#Table-of-Contents)

**Data Type objects** are instances of the ```numpy.dtype``` class. The data type object can tell you the size of the data in bytes.

A data type object describes interpretation of fixed block of memory corresponding to an array, depending on the following aspects:
- Type of data(int, float,or Python object)
- Size of data
- Byte order(little-endian or big-endian)
- In case of Structured type, the names of fiels, data type of each field and part of the memory block taken by each field.
- If data type is subarray, its shape and data type.

The byte order is decided by prefixing '<' ot '>' to data type. 

- '<' means that encoding is little-endian(least significant is stored in smallest address).
- '>' means that encoding is big-endian(most significanat byte is stored in smallest address).

A dtype object is constructed using the following syntax:
```python
numpy.dtype(object, align, copy)
```

The parameters are:
- **object**- To be converted to data type object
- **Align**- If True, adds padding to the field to make it similar to C-struct.
- **Copy**- Makes a new copy of dtype object. If False, the result is reference to builtin data type object

The size in bytes is given by the ```object.dtype.itemsize```

#### Character Codes
**Character Codes** are included for backward compatibility with Numeric. Their use is not recommended. Each Built-in data type has a character code that uniquely identifies it.

| **Type**               | **Character Code** |
|------------------------|--------------------|
| Integer                | i                  |
| Unsigned integer       | u                  |
| Single Precision float | f                  |
| Double precision float | d                  |
| Boolean                | b                  |
| Complex                | D                  |
| String                 | S                  |
| Unicode                | U                  |
| Void                   | V                  |

In [11]:
# 1. using array-scalar type
dt = np.dtype(np.int32)
dt

dtype('int32')

In [12]:
# 2. #int8, int16, int32, int64 can be replaced by 
# equivalent string 'i1', 'i2','i4', etc.
dt = np.dtype('i4')
dt

dtype('int32')

In [13]:
# 3. Using endian notation
dt = np.dtype('>i4')
dt

dtype('>i4')

#### Structured Data Type
[back to top](#Table-of-Contents)

Here, the field name and the corresponding scalar data type is to be declared.

In [14]:
# create structured data type
dt = np.dtype([('age', np.int8)])
dt

dtype([('age', 'i1')])

In [15]:
# apply it to ndarray object
a = np.array([(10,), (20,), (30,)], dtype= dt)
print(a)

[(10,) (20,) (30,)]


In [16]:
# file name can be used to access content of age column
print(a['age'])

[10 20 30]


The following examples define a structured data type called **team** with a string field 'name', an **integer field** 'ranking' and a **float field** 'points'. This dtype is applied to ndarray object.

In [17]:
team = np.dtype([('name', 'S20'), ('ranking', 'i1'), ('points', 'f4')])
team

dtype([('name', 'S20'), ('ranking', 'i1'), ('points', '<f4')])

In [18]:
a = np.array([('Real Madrid', 2, 85), ('Bayern Munich', 1, 90)], dtype=team)
print(a)

[(b'Real Madrid', 2,  85.) (b'Bayern Munich', 1,  90.)]


## Array Attributes
[back to top](#Table-of-Contents)

### ```ndarray.shape```
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [19]:
a = np.array([np.arange(3), np.arange(3)])
a.shape

(2, 3)

In [20]:
# Resize the ndarray
a.shape=(3,2)
a

array([[0, 1],
       [2, 0],
       [1, 2]])

In [21]:
# Using reshape function
print(a)
b = a.reshape(6, 1)
print('\n\n',b)

[[0 1]
 [2 0]
 [1 2]]


 [[0]
 [1]
 [2]
 [0]
 [1]
 [2]]


### ```ndarray.ndim```
This array attribute returns the number of array dimensions.

In [22]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
a.ndim

1

In [24]:
# Reshape it
b = a.reshape(2,4,3)
print('b is having three dimensions\n\n', b)

b is having three dimensions

 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [25]:
print('dimension: ',b.ndim)
print('shape: ', b.shape)

dimension:  3
shape:  (2, 4, 3)


### ```ndarray.itemsize```
This array attribute returns the length of each element of array in bytes.

In [26]:
x = np.array(np.arange(1,6), dtype=np.int8)
x

array([1, 2, 3, 4, 5], dtype=int8)

In [27]:
x.itemsize

1

In [28]:
x = np.array(np.arange(1, 6), dtype=np.float32)
x.itemsize

4

### ```ndarray.flags```


In [29]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False