![](https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei)
<img src="http://www.scipy-lectures.org/_images/numpy_broadcasting.png" height="300" width="500">


<h1 id="tocheading">Table of Contents</h1>
<div id="toc"></div>

<h1 align="center">Beginning with NumPy Fundamentals</h1>
## Import packages

In [1]:
import sys
from datetime import datetime
import time
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

## NumPy Ndarray object
NumPy has a multidimensional array object called ```ndarray```. It consists of two parts:
- The actual data
- Some metadata describing the data

The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ```ndarray``` takes the same size of block in the memory. Each element is an object of data-type object called **dytpe**.

Any item extracted from ```ndarray``` object(by slicing) is represented by a Python object of one of array scalar types.

*Relationship between ```ndarray```, data type object(dtype) and array scalar type*

![](https://www.tutorialspoint.com/numpy/images/ndarray.jpg)

The ```ndarray``` object can have more than one dimension.

An instance of ndarray class can be constructed by different array creation routines described later in the tutorial. The basic ndarray is created using an array function in NumPy as follows

```python
numpy.array
```

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

```python 
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
```

| **Parameter** | **Description**                                                                                  |
|---------------|--------------------------------------------------------------------------------------------------|
| **object**    |  Any object exposing the array interface method returns an array,  or any (nested) sequence.     |
| **dtype**     |  Desired data type of array, optional                                                            |
| **copy**      | Optional. By default (true), the object is copied                                                |
| **order**     | C (row major) or F (column major) or A (any) (default)                                           |
| **subok**     | By default, returned array forced to be a base class array.  If true, sub-classes passed through |
| **ndimin**    | Specifies minimum dimensions of resultant array                                                  |

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(5,)

### Creating a multidimensional array

In [5]:
m = np.array([np.arange(2), np.arange(2)])
m

array([[0, 1],
       [0, 1]])

In [6]:
m.shape

(2, 2)

In [7]:
n = np.array([np.arange(3), np.arange(3), np.arange(3)])
n

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
n.shape

(3, 3)

### Minimum dimensions

In [9]:
a = np.array(np.arange(5), ndmin=2)
a

array([[0, 1, 2, 3, 4]])

### dytype parameter

In [10]:
a = np.array(np.arange(5), dtype=complex)
a

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j])

The **```ndarray```** object consists of contiguous one-dimensional segment of computer memory, combined with an indexing scheme that maps each item to a location in the memory block. The memory block holds the elements in a row-major order (C style) or a column-major order (FORTRAN or MatLab style).



## NumPy Data Types

In [11]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [12]:
a.shape

(2, 2)

In [13]:
a[0,0]

1

In [14]:
a[1,1]

4

## NumPy numerical types

## Type Conversions

## Array Creation

## Indexing

## Slicing

## Shape Manipulation

In [17]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')
script-src 'self' https://www.google-analytics.com data:

<IPython.core.display.Javascript object>

<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline' https: 'unsafe-inline' www.google-analytics.com ajax.googleapis.com;">